[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "chainlit run app.py --port $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 