services:
  - type: web
    name: ewantaistu
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: chainlit run app.py --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
    autoDeploy: true 