services:
  - type: web
    name: ewantaistu
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: chainlit run app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PYTHONUNBUFFERED
        value: "true"
    autoDeploy: true 