[project]
enable_telemetry = true
user_env = []

[UI]
name = "AI教學助手"
default_collapse_content = true
language = "zh-TW"

[auth]
type = "credentials"
enabled = true
require_auth = true
allow_registration = true

[features]
unsafe_allow_html = true
